In [21]:
import torch
import numpy as np

In [22]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [23]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [24]:
# Retain the properties of x_data (shape, datatype)
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: {x_ones}")

# Overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor: {x_rand}")

Ones tensor: tensor([[1, 1],
        [1, 1]])
Random tensor: tensor([[0.5660, 0.4910],
        [0.4131, 0.4895]])


In [25]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: {rand_tensor}")
print(f"Ones tensor: {ones_tensor}")
print(f"Zeros tensor: {zeros_tensor}")

Random tensor: tensor([[0.6315, 0.8528, 0.2140],
        [0.5032, 0.2052, 0.8073]])
Ones tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [26]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [27]:
# Move tensor to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [28]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [30]:
# Element wise product
print(f"{tensor.mul(tensor)=}")

# Alternative syntax
print(f"{tensor * tensor=}")

tensor.mul(tensor)=tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor * tensor=tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [31]:
# Matrix multiplication between two tensors
print(f"{tensor.matmul(tensor.T)=}")
# Alternative syntax
print(f"{tensor @ tensor.T=}")

tensor.matmul(tensor.T)=tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor @ tensor.T=tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [32]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [33]:
t = torch.ones(5)
print(f"{t=}")
n = t.numpy()
print(f"{n=}")

t=tensor([1., 1., 1., 1., 1.])
n=array([1., 1., 1., 1., 1.], dtype=float32)


In [34]:
t.add_(1)
print(f"{t=}")
print(f"{n=}")

t=tensor([2., 2., 2., 2., 2.])
n=array([2., 2., 2., 2., 2.], dtype=float32)


In [35]:
n = np.ones(5)
t = torch.from_numpy(n)

In [36]:
np.add(n, 1, out=n)
print(f"{t=}")
print(f"{n=}")

t=tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n=array([2., 2., 2., 2., 2.])
